export const dummyPosts = [
  {
    id: "1",
    title: "Open Source is so Awesome",
    shortDescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    upvotes: 2,
    downvotes: 0,
    commentsCount: 0,
    author: "JohnDoe",
    createdAt: new Date(),
    subredditName: "opensource",
    content: "This is a demo content for the post.",
    image: "",
  },
  {
    id: "2",
    title: "Why I Love TypeScript",
    shortDescription: "TypeScript makes JavaScript development smoother.",
    upvotes: 15,
    downvotes: 1,
    commentsCount: 5,
    author: "JaneSmith",
    createdAt: new Date(),
    subredditName: "typescript",
    content: "Here's why TypeScript has become essential for me...",
    image: "",
  },
  {
    id: "3",
    title: "React vs Vue: My Experience",
    shortDescription: "React and Vue are both popular frontend frameworks.",
    upvotes: 23,
    downvotes: 3,
    commentsCount: 12,
    author: "AlexCoder",
    createdAt: new Date(),
    subredditName: "webdev",
    content: "I spent a year using both frameworks. Here's my take...",
    image: "",
  },
  {
    id: "4",
    title: "Docker for Beginners",
    shortDescription: "A quick start guide for Docker.",
    upvotes: 7,
    downvotes: 0,
    commentsCount: 4,
    author: "DevOpsDiva",
    createdAt: new Date(),
    subredditName: "devops",
    content: "Docker simplifies application deployment by using containers...",
    image: "",
  },
  {
    id: "5",
    title: "Python vs JavaScript for Data Science",
    shortDescription: "Comparing Python and JavaScript for data tasks.",
    upvotes: 9,
    downvotes: 2,
    commentsCount: 6,
    author: "DataGeek",
    createdAt: new Date(),
    subredditName: "datascience",
    content: "Let's compare the two languages and see where each excels...",
    image: "",
  },
  {
    id: "6",
    title: "5 Tips to Improve Coding Productivity",
    shortDescription: "Boost your coding productivity with these tips.",
    upvotes: 20,
    downvotes: 0,
    commentsCount: 8,
    author: "ProCoder",
    createdAt: new Date(),
    subredditName: "productivity",
    content: "Here are my top tips to stay productive while coding...",
    image: "",
  },
  {
    id: "7",
    title: "Is AI Going to Replace Developers?",
    shortDescription: "Exploring the impact of AI on software jobs.",
    upvotes: 12,
    downvotes: 4,
    commentsCount: 10,
    author: "AIEnthusiast",
    createdAt: new Date(),
    subredditName: "artificialintelligence",
    content: "As AI advances, how will it impact the role of developers?",
    image: "",
  },
  {
    id: "8",
    title: "Building My First Full-Stack App",
    shortDescription: "A journey through building a full-stack application.",
    upvotes: 14,
    downvotes: 1,
    commentsCount: 7,
    author: "NewDev",
    createdAt: new Date(),
    subredditName: "learnprogramming",
    content: "Building my first app taught me a lot about web development...",
    image: "",
  },
  {
    id: "9",
    title: "Best Practices for REST APIs",
    shortDescription: "Make your REST API reliable and easy to use.",
    upvotes: 18,
    downvotes: 0,
    commentsCount: 9,
    author: "APIWizard",
    createdAt: new Date(),
    subredditName: "backend",
    content: "A well-designed API is essential for great software...",
    image: "",
  },
  {
    id: "10",
    title: "Exploring GraphQL",
    shortDescription: "A look into the GraphQL query language.",
    upvotes: 10,
    downvotes: 2,
    commentsCount: 5,
    author: "GraphQLGuru",
    createdAt: new Date(),
    subredditName: "graphql",
    content: "GraphQL offers a flexible way to interact with your data...",
    image: "",
  },
];
